openapi: 3.0.1
info:
  title: Web Market
  version: '0.1'
externalDocs:
  url: https://github.com/lucianoScotellaro/SWA-WebMarketRESTfulAPI.git
  description: GitHub repository of the project
servers:
  - url: http://localhost:8080/webmarket/rest
tags:
  - name: Request
    description: Operations on a single request
  - name: Requests Collection
    description: Operations on requests collection
  - name: Request property
    description: Operations on requests properties
  - name: Proposal
    description: Operations on a single proposal
  - name: Proposal property
    description: Operations on proposals properties
paths:
  /requests:
    post:
      operationId: addRequest
      description: add new request
      tags:
        - Request
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '201':
          $ref: '#/components/responses/SuccessfulInsert'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  /requests/current/{ordererid}:
    get:
      operationId: getOrdererCurrentRequests
      description: Returns open requests for an orderer
      tags:
        - Requests Collection
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/OrdererID'
      responses:
        '200':
          description: Orderer open requests base info list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrdererBaseRequestsList'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  /requests/unassigned:
    get:
      operationId: getUnassigned
      description: Returns requests that have not been assigned to a technician
      tags:
        - Requests Collection
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Unassigned requests base info list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnassignedRequestsList'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  /requests/{techemail}:
    get:
      operationId: getTechnicianRequests
      description: Returns requests handled by the technician
      tags:
        - Requests Collection
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TechnicianEmail'
      responses:
        '200':
          description: Technician requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TechnicianBaseRequestsList'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  /requests/{requestid}:
    delete:
      operationId: deleteRequest
      description: Delete a request
      tags:
        - Request
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/RequestID'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  /requests/{requestid}/technicianEmail:
    patch:
      operationId: addTechnician
      description: Binds a technician to a request
      tags:
        - Request
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/RequestID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  /requests/{requestid}/proposal:
    get:
      operationId: getProposal
      description: Returns proposal associated to the request
      tags:
        - Request
        - Proposal
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/RequestID'
      responses:
        '200':
          description: Proposal associated to the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Proposal'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
    post:
      operationId: addProposal
      description: Add a proposal for a request
      tags:
        - Request property
        - Proposal
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/RequestID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proposal'
      responses:
        '201':
          $ref: '#/components/responses/SuccessfulInsert'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
    patch:
      operationId:  updateProposal
      description: Update proposal for a request
      tags:
        - Request property
        - Proposal
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/RequestID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proposal'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
  /requests/{requestid}/proposal/response:
    patch:
      operationId: addResponse
      description: Add response for a proposal
      tags:
        - Proposal property
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/RequestID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Response'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/GeneralError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: internalToken
  schemas:
    ID:
      type: integer
      minimum: 1
    Email:
      type: string
      format: email
    User:
      type: object
      properties:
        email:
          $ref: '#/components/schemas/Email'
        username:
          type: string
      required:
        - email
        - username
      additionalProperties: false
    Product:
      type: object
      properties:
        name:
          type: string
        producer:
          type: string
        id:
          $ref: '#/components/schemas/ID'
        price:
          type: number
          minimum: 0
        url:
          type: string
      required:
        - name
        - producer
        - id
        - price
        - url
      additionalProperties: false
    Proposal:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/Product'
        notes:
          type: string
        response:
          $ref: '#/components/schemas/Response'
      required:
        - product
        - notes
        - response
      additionalProperties: false
    Request:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ID'
        orderer:
          $ref: '#/components/schemas/User'
        technician:
          $ref: '#/components/schemas/User'
        category:
          type: string
        characteristics:
          type: object
        notes:
          type: string
        proposal:
          $ref: '#/components/schemas/Proposal'
        ongoing:
          type: boolean
        outcome:
          type: string
          enum:
            - Accepted
            - Rejected as non compliant
            - Rejected as defective
      required:
        - id
        - orderer
        - technician
        - category
        - characteristics
        - notes
        - proposal
        - ongoing
        - outcome
      additionalProperties: false
    OrdererBaseRequestsList:
      type: array
      items:
        type: object
        properties:
          id:
            $ref: '#/components/schemas/ID'
          technician:
            $ref: '#/components/schemas/User'
          category:
            type: string
        required:
          - id
          - technician
          - category
    UnassignedRequestsList:
      type: array
      items:
        type: object
        properties:
          id: 
            $ref: '#/components/schemas/ID'
          orderer:
            $ref: '#/components/schemas/User'
          category:
            type: string
          characteristics:
            type: object
          notes: 
            type: string
        required:
          - id
          - orderer
          - category
          - characteristics
          - notes
    TechnicianBaseRequestsList:
      type: array
      items:
        type: object
        properties:
          id:
            $ref: '#/components/schemas/ID'
          orderer:
            $ref: '#/components/schemas/User'
          category:
            type: string
        required:
          - id
          - orderer
          - category
    Response:
      type: object
      properties:
        accepted:
          type: boolean
        reason:
          type: string
      required:
        - accepted
        - reason
      additionalProperties: false
  parameters:
    RequestID:
      name: requestid
      in: path
      required: true
      schema: 
        $ref: '#/components/schemas/ID'
    ProposalID:
      name: proposalid
      in: path
      required: true
      schema: 
        $ref: '#/components/schemas/ID'
    OrdererID:
      name: ordererid
      in: path
      required: true
      schema: 
        $ref: '#/components/schemas/ID'
    TechnicianEmail:
      name: techemail
      in: path
      required: true
      schema: 
        $ref: '#/components/schemas/Email'
  responses:
    SuccessfulInsert:
     description: Element created
     headers:
      location:
        schema:
         type: string
         format: uri
     content:
      application/json:
       schema:
        type: string
        format: uri
    NoContent:
      description: No content
    GeneralError:
      description: General error
    UnauthorizedError:
      description: Missing or invalid bearer token
    NotFound:
     description: Element not found
     content:
      text/plain:
       schema:
        type: string
        example: Not found
  